### ISSUE TITLE
If it is a file type image, the UI will not be refreshed

### ISSUE THREAD

**Issue by tudosxxx** [RafaelBarbosatec/gif_view#14]
String _getKeyImage(ImageProvider provider) {
    return provider is NetworkImage
        ? provider.url
        : provider is AssetImage
        ? provider.assetName
        : provider is MemoryImage
        ? provider.bytes.toString()
        : provider is FileImage  // add this
        ? provider.file.path : "";
  }

**Comment by tudosxxx** [comment]
2.Refresh every time you close the page


onFrame?.call(currentIndex);
notifyListeners();  this line
_run();

E/flutter (17534): Once you have called dispose() on a GifController, it can no longer be used.
E/flutter (17534): #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:157:9)
E/flutter (17534): #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:164:6)
E/flutter (17534): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:360:27)
E/flutter (17534): #3      GifController._runNextFrame (package:gif_view/src/gif_controller.dart:67:5)

**Comment by tudosxxx** [comment]
3.I back to a page and refresh the UI, which will speed up the playback of gif。
GifPage  to BPage_back(result: "aaa")    GifPage  setstate((){});
